# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c70058d5a916e0c4fa4072e8fc0d5ad7ff4f62b09db83962cb53b06651fba68740c6d4e67a13adba772722e18b4ffa48f806c016abba7bf58c8a56f46644ead8

test:
  secret_key_base: fd2feb26c5ce67f4babf5b1ebf38884b061c96e91e97a8052f1cf9fddf55f87b4073cfa62341a1bd34a7e73036e261308a8861a4567a18502119736ddf2a27e3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
